version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/notes-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      APPLICATION_SECURITY_UUID: b592691e-df3f-4049-86d5-50bdce269354
      APPLICATION_SECURITY_SYSTEM_USERNAME: SYSTEM
      APPLICATION_SECURITY_SYSTEM_PASSWORD: SYSTEM
    volumes:
      - ./src/main/resources/key/ES512.json:/opt/resources/key/ES512.json

  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
